---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      apt:
        name: python3-pip
        state: present

    - name: Add Docker repository key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install docker-py python module
      pip:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start the container
      docker_container:
        name: hariapp
        image: "nazx/hariapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          0.0.0.0:8081:8080
