---
- hosts: dev                               ---> this playbook is not for UBUNTU Server this is for centos. This will cause error in ubuntu server
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: start docker
      service:
        name: snap.docker.dockerd
        state: started
        enabled: yes
    - name: Start the container
      docker_container:
        name: hariapp
        image: "nazx/hariapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          0.0.0.0:8081:8080
